class MyTokens
  @program1_tokens = [
    {kind: 'ID', lexeme:'x', start: 0},
    {kind: ':=', lexeme:':=', start: 2},
    {kind: 'INTLIT', lexeme:'2', start: 5},
    {kind: '*', lexeme:'*', start: 7},
    {kind: 'INTLIT', lexeme:'3', start: 9},
    {kind: 'newline', lexeme: 'newline', start: 10},
    {kind: 'ID', lexeme: 'y', start: 0},
    {kind: ':=', lexeme: ':=', start: 2},
    {kind: 'INTLIT', lexeme: '8', start: 5},
    {kind: '/', lexeme: '/', start: 7},
    {kind: 'INTLIT', lexeme: '4', start: 9},
    {kind: 'newline', lexeme: 'newline', start: 10},
    {kind: 'ID', lexeme: 'x', start: 0},
    {kind: '=', lexeme: '=', start: 2},
    {kind: 'ID', lexeme: 'x', start: 4},
    {kind: '*', lexeme: '*', start: 6},
    {kind: 'ID', lexeme: 'y', start: 8},
    {kind: 'newline', lexeme: 'newline', start: 9},
    {kind: 'ID', lexeme: 'newFunc', start: 0},
    {kind: ':=', lexeme: ':=', start: 8},
    {kind: '(', lexeme: '(', start: 11},
    {kind: 'ID', lexeme: 'x', start: 12},
    {kind: ', ', lexeme: ', ', start: 13},
    {kind: 'ID', lexeme: 'y', start: 15},
    {kind: ')', lexeme: ')', start: 16},
    {kind: '->', lexeme: '->', start: 18},
    {kind: 'newline', lexeme: 'newline', start: 20},
    {kind: 'return', lexeme: 'return', start: 4},
    {kind: 'ID', lexeme: 'x', start: 11},
    {kind: 'if', lexeme: 'if', start: 13},
    {kind: 'ID', lexeme: 'x', start: 16},
    {kind: '>=', lexeme: '>=', start: 18},
    {kind: 'ID', lexeme: 'y', start: 21},
    {kind: 'else', lexeme: 'else', start: 23},
    {kind: 'true', lexeme: 'true', start: 28},
    {kind: 'newline', lexeme: 'newline', start: 32},
    {kind: 'end', lexeme: 'end', start: 0},
    {kind: 'newline', lexeme: 'newline', start: 3}
    ]

  @program2_tokens = [
    {kind:'ID', lexeme:'x', start:0},
    {kind:':=', lexeme:':=', start:2},
    {kind:'INTLIT', lexeme:'2', start:5},
    {kind:'newline', lexeme:'newline', start:6},
    {kind:'ID', lexeme:'x', start:0},
    {kind:'++', lexeme:'++', start:1},
    {kind:'newline', lexeme:'newline', start:3},
    {kind:'ID', lexeme:'x', start:0},
    {kind:'+=', lexeme:'+=', start:2},
    {kind:'INTLIT', lexeme:'2', start:5},
    {kind:'newline', lexeme:'newline', start:6},
    {kind:'ID', lexeme:'collatz', start:0},
    {kind:':=', lexeme:':=', start:8},
    {kind:'(', lexeme:'(', start:11},
    {kind:'ID', lexeme:'x', start:12},
    {kind:')', lexeme:')', start:13},
    {kind:'->', lexeme:'->', start:15},
    {kind:'newline', lexeme:'newline', start:17},
    {kind:'ID', lexeme:'out', start:4},
    {kind:'(', lexeme:'(', start:7},
    {kind:'ID', lexeme:'x', start:8},
    {kind:')', lexeme:')', start:9},
    {kind:'newline', lexeme:'newline', start:10},
    {kind:'return', lexeme:'return', start:4},
    {kind:'ID', lexeme:'x', start:11},
    {kind:'if', lexeme:'if', start:13},
    {kind:'ID', lexeme:'x', start:16},
    {kind:'is', lexeme:'is', start:18},
    {kind:'INTLIT', lexeme:'1', start:21},
    {kind:'else', lexeme:'else', start:23},
    {kind:'(', lexeme:'(', start:28},
    {kind:'ID', lexeme:'collatz', start:30},
    {kind:'(', lexeme:'(', start:37},
    {kind:'ID', lexeme:'x', start:38},
    {kind:'/', lexeme:'/', start:39},
    {kind:'INTLIT', lexeme:'2', start:40},
    {kind:')', lexeme:')', start:41},
    {kind:'if', lexeme:'if', start:43},
    {kind:'ID', lexeme:'x', start:46},
    {kind:'%', lexeme:'%', start:48},
    {kind:'INTLIT', lexeme:'2', start:50},
    {kind:'is', lexeme:'is', start:52},
    {kind:'INTLIT', lexeme:'0', start:55},
    {kind:'else', lexeme:'else', start:57},
    {kind:'ID', lexeme:'collatz', start:62},
    {kind:'(', lexeme:'(', start:69},
    {kind:'INTLIT', lexeme:'3', start:70},
    {kind:'*', lexeme:'*', start:71},
    {kind:'ID', lexeme:'x', start:72},
    {kind:'+', lexeme:'+', start:73},
    {kind:'INTLIT', lexeme:'1', start:74},
    {kind:')', lexeme:')', start:75},
    {kind:')', lexeme:')', start:76},
    {kind:'newline', lexeme:'newline', start:77},
    ]
module.exports = MyTokens